Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -67,6 +67,30 @@ runs:
         echo "no" | $HOME/android-sdk/cmdline-tools/tools/bin/avdmanager create avd -n emu -k "system-images;android-${{ inputs.api-level }};google_apis;x86_64" --device "pixel" > /dev/null 2>&1
       shell: bash
 
+    - name: Config emulator
+      run: |
+          AVD_PATH="$HOME/.android/avd/emu.avd/config.ini"
+          
+          # Ensure AVD exists before modifying
+          if [ -f "$AVD_PATH" ]; then
+              echo "Modifying emulator config..."
+              echo "hw.cpu.ncore=4" >> "$AVD_PATH"
+              echo "hw.ramSize=4096" >> "$AVD_PATH"
+              echo "hw.heapSize=512" >> "$AVD_PATH"
+              echo "disk.dataPartition.size=6G" >> "$AVD_PATH"
+              echo "hw.keyboard=yes" >> "$AVD_PATH"
+          else
+              echo "AVD not found! Skipping configuration."
+              exit 1
+          fi
+    
+          # Disable hardware acceleration on Linux (if needed)
+          if [[ "$RUNNER_OS" == "Linux" ]]; then
+              echo "Disabling Linux hardware acceleration"
+              echo "ANDROID_EMULATOR_OPTIONS=-accel off" >> $GITHUB_ENV
+          fi
+      shell: bash
+
     - name: Start Android emulator
       run: |
           nohup $HOME/android-sdk/emulator/emulator -port 5554 -avd emu -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim &
