Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -98,13 +98,27 @@ runs:
 
     - name: Wait for Emulator to Boot
       run: |
-        boot_completed=""
-        while [ "$boot_completed" != "1" ]; do
+        bootanim=""
+        failcounter=0
+        timeout_in_sec=500
+        until [[ "$bootanim" =~ "stopped" ]]; do
+          bootanim=$(adb -e shell getprop init.svc.bootanim 2>/dev/null || true)
+          echo "Boot animation status: $bootanim"
+          if [[ "$bootanim" =~ "not found"
+            || "$bootanim" =~ "device not found"
+            || "$bootanim" =~ "no emulators found"
+            || "$bootanim" =~ "device offline"
+            || "$bootanim" =~ "running" ]]; then
+            ((failcounter+=5))
+            echo "$bootanim"
+            if [[ $failcounter -gt $timeout_in_sec ]]; then
+              echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
+              exit 1
+            fi
+          fi
           sleep 5
-          boot_completed=$($ANDROID_HOME/platform-tools/adb -s emulator-5554 shell getprop sys.boot_completed || true)
-          echo "Waiting for emulator to boot..."
         done
-        echo "Emulator has booted!"
+        echo "Emulator is ready!"
       shell: bash
     
     - name: Unlock Emulator
